version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: local-docker
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: docs_protocol
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - postgres_network
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  postgres_network:
    driver: bridge