server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/docs_protocol
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: admin
      role: USER

logging:
  level:
    org.springframework.security: DEBUG